### ISSUE TITLE
Headless rendering issue for environments with doors

### ISSUE THREAD

**Issue by mbchang** [mila-iqia/babyai#86]
Hi, I am experiencing an issue rendering the frames using `env.render(mode='rgb_array')`. For some reason this issue seems to be specific to environments that contain doors. The rendering looks like this:

![image](https://user-images.githubusercontent.com/6439365/68537527-6d89c580-031a-11ea-81d4-ebbe56eb11b5.png)

Attached is an ipython notebook with some examples. This seems to be an issue with both the BabyAI and Minigrid environments. Would you have some pointers or suggestions on how to fix this?

[Debug Rendering.pdf](https://github.com/mila-iqia/babyai/files/3827980/Debug.Rendering.pdf)

Thanks!

**Comment by rizar** [comment]
@maximecb

**Comment by maximecb** [comment]
Looking at the issue.

**Comment by maximecb** [comment]
![Screenshot_2019-11-11_10-58-30](https://user-images.githubusercontent.com/713766/68601528-80afa900-0472-11ea-9c52-ff50881b0110.png)

So, it seems to work fine on my end using the latest MiniGrid pull from GitHub and matplotlib without the agg backend. I wonder if it could be an issue with your setup because this environment is not square, rather than the fact that it has a door.

@mbchang Could you try `debug_rendering('BabyAI-GoTo-v0')` and let us know if that works or not?

**Comment by maximecb** [comment]
EDIT: it also works fine with the agg backend and saving the figure to PNG

@mbchang The figure should be a rectangle that's twice as wide as it's tall, but your rendering shows it as twice as tall as it's wide. I think you have to either transpose the first and second dimensions , or reinterpret the data as having the dimensions transposed.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html

Try it and let us know how it works.

**Comment by mbchang** [comment]
@maximecb you are right, thank you! I reshaped the frame and now it looks as expected:

![image](https://user-images.githubusercontent.com/6439365/68617126-65956700-047b-11ea-91ef-ffe71c31ea7c.png)

Thank you so much!
